const BOX_DRAG_STOKE_WIDTH = 7.5;
const CIRCLE_DRAG_STOKE_WIDTH = 7.5;
const ARROW_DRAG_STROKE_WIDTH = 7.5;
const TEXT_BOX_DRAG_STROKE_WIDTH = 7.5;
const DIAMOND_DRAG_STROKE_WIDTH = 7.5;
const SHAPE_HOVER_STROKE_COLOR = "oklch(72% 0.18 255)";

export {
  BOX_DRAG_STOKE_WIDTH,
  CIRCLE_DRAG_STOKE_WIDTH,
  ARROW_DRAG_STROKE_WIDTH,
  TEXT_BOX_DRAG_STROKE_WIDTH,
  DIAMOND_DRAG_STROKE_WIDTH,
  SHAPE_HOVER_STROKE_COLOR,
};
