const BOX_DRAG_STOKE_WIDTH = 15;
const CIRCLE_DRAG_STOKE_WIDTH = 15;
const ARROW_DRAG_STROKE_WIDTH = 15;
const TEXT_BOX_DRAG_STROKE_WIDTH = 10;
const DIAMOND_DRAG_STROKE_WIDTH = 15;

export {
  BOX_DRAG_STOKE_WIDTH,
  CIRCLE_DRAG_STOKE_WIDTH,
  ARROW_DRAG_STROKE_WIDTH,
  TEXT_BOX_DRAG_STROKE_WIDTH,
  DIAMOND_DRAG_STROKE_WIDTH,
};
