import type { Metadata } from "next";
import { Playwrite_AU_QLD } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";

const playwrite_au_qld = Playwrite_AU_QLD({
  variable: "--playwrite-au-qld",
  weight: "200",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playwrite_au_qld.className}`}>
      <body
        className={`${playwrite_au_qld.className} color-base-100 color-base-content p-1`}
      >
        <ToastContainer toastClassName={`${playwrite_au_qld.className}`}  />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
